development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://lzgvuicfejnqqo:e08fc7633a0ee3b4131717453966614b8b78c0bb360bf98ec7e43cd459eab819@ec2-54-243-38-139.compute-1.amazonaws.com:5432/d5n3gbrk2vssd9
